### ISSUE TITLE
Cannot access theme carousel easily in event description page

### ISSUE THREAD

**Issue by khojjat** [kmblake/foodiez#18]
The theme carousel goes to bottom of page when selecting a time. I cannot access the themes again unless I click back onto the date entry form. "choose your own" still totally visible without themes
![img_8582](https://cloud.githubusercontent.com/assets/28642410/26016874/aec4ec6e-371b-11e7-8bb1-43fc818e0401.PNG)

**Comment by kmblake** [comment]
Fixed. You can either tap on "Choose Seasonal Menu" or tap on the Time field to close the time picker
