### ISSUE TITLE
Limited Scrolling on Attendee List

### ISSUE THREAD

**Issue by khojjat** [kmblake/foodiez#5]
When scrolling through attendee list on an event invitation, page does not respond to scroll. List jumps back up to original position and does not allow you to see the entire invitation. 
![img_8580](https://cloud.githubusercontent.com/assets/28642410/26016196/e82d41fc-3718-11e7-9a76-560710fa4836.PNG)

**Comment by kmblake** [comment]
Should be fixed, please confirm @khojjat
